language: node_js
services:
- docker
cache:
  directories:
  - $HOME/.npm
notifications:
  email: false
node_js: 7
before_install:
- npm install -g npm@5.2.0
install: npm install
after_success: npm run deploy
branches:
  except:
  - /^v\d+\.\d+\.\d+$/
